### ISSUE TITLE
Example usage in the synopsis is not working

### ISSUE THREAD

**Issue by eazar001** [mndrix/interpolate#1] opened 2015-03-07 22:52 UTC
The example in the synopsis (from your README.md file) is not working as of swi-prolog version 7.1.32.

Expected behavior: objects should be subsituted with the appropriate contents of the variables.
Observed behavior: the original string is returned.

**Comment by mndrix** [comment] 2015-03-07 23:49
Thanks for the report @eazar001  I wasn't able to reproduce this locally.  Below is a transcript of the code I tried.  What output does it give you?

```
$ cat synopsis.pl
:- use_module(library(interpolate)).
main :-
    Name = "Johannson",
    Time = evening,
    writeln('Hello Mr. $Name. Isn''t it a fine $Time?').

$ swipl -q -t main -s synopsis.pl
Warning: /Users/michael/src/prolog/interpolate/synopsis.pl:2:
        Singleton variables: [Name,Time]
Hello Mr. "Johannson". Isn't it a fine evening?
```

In commit 7bc5b97e48579e83f99c269a10f7024dca4deb2d I've fixed the extra quote characters around `Johannson`.  I'll release that fix once I can address your issue.

The `Singleton variables` warning is unavoidable with SWI-Prolog's current reader.  I usually do `_=Name, _=Time` in this context if they come up.

**Comment by eazar001** [comment] 2015-03-07 23:58
Thanks for your response @mndrix. Apparently I was doing the same thing that you were doing with one exception: I was testing it exclusively at the swipl prompt like such:

`?- use_module(library(interpolate)), Name = "John", writeln('Hello $Name').`

If I do it that way it fails. However, if I make a predicate like your example above, it works.

**Comment by eazar001** [comment] 2015-03-08 00:00
Thank you for clearing that up for me. However, while the functionality works just fine for me now, I'm still unclear as to whether or not this is intended/desirable behavior for you. Therefore, I'll leave this issue open so that you can close it at your discretion. Thank you again.

**Comment by mndrix** [comment] 2015-03-09 14:40
It looks like this is a bug in the way that `prolog_load_context/2` works.  I've created #2 to track this.  Closing.

**Closed as completed by mndrix** 2015-03-09 14:40 UTC
